# Generated by Django 5.2.5 on 2025-12-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_menuitem_image_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Pick up at restaurant', max_length=255),
        ),
    ]
