# Generated by Django 5.2.5 on 2025-12-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='extra_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='base_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
        ),
    ]
