# Generated by Django 5.2.8 on 2026-03-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_image', models.ImageField(blank=True, null=True, upload_to='app_config/')),
                ('welcome_title', models.CharField(default='Eminence Eatz', max_length=100)),
                ('welcome_subtitle', models.TextField(default='Order your favorite meals from top restaurants in Ghana.')),
                ('promo_text', models.CharField(blank=True, default='FREE DELIVERY', max_length=100)),
            ],
            options={
                'verbose_name': 'App Configuration',
            },
        ),
    ]
