# Generated by Django 5.2.8 on 2026-03-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_appconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
