# Generated by Django 5.2.8 on 2026-03-16 03:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_appconfig_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='welcome_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
